---
project_name: livesplit-race-manager
builds:
  - id: livesplit-race-manager
    binary: livesplit-race-manager
    main: ./cmd/livesplit-race-manager/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - id: livesplit-race-manager-archive
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - id: docker_livesplit-race-manager
    ids:
      - livesplit-race-manager
    image_templates:
      - "ghcr.io/fuhrmannb/livesplit-race-manager:{{ .Tag }}"
      - "ghcr.io/fuhrmannb/livesplit-race-manager:latest"
